**DATA CREATION**

In [1]:
import numpy as np
student=np.array(['Akhil','Sia','Lia'])
subjects=np.array(['Maths','English','science','Social'])
marks=np.array([[89,56,87,67],
               [78,56,46,90],
               [98,89,90,78]])
print(student)
print(subjects)
print(marks)

['Akhil' 'Sia' 'Lia']
['Maths' 'English' 'science' 'Social']
[[89 56 87 67]
 [78 56 46 90]
 [98 89 90 78]]


**DATA EXPLORATION**

**Dimension**

In [2]:
print(student.ndim)
print(subjects.ndim)
print(marks.ndim)

1
1
2


**Size**

In [3]:
print(student.size)
print(subjects.size)
print(marks.size)

3
4
12


**Structure**

In [4]:
print(student.shape)
print(subjects.shape)
print(marks.shape)

(3,)
(4,)
(3, 4)


**DATA TRANSFORMATION**

**Reshape**

In [5]:
reshaped = marks.reshape(4,3)
print(reshaped)

[[89 56 87]
 [67 78 56]
 [46 90 98]
 [89 90 78]]


**Recognisation**

In [6]:
for i, stud in enumerate(student):
    print(f"\nStudent: {stud}")
    for j, subj in enumerate(subjects):
        print(f"{subj}: {marks[i, j]}")



Student: Akhil
Maths: 89
English: 56
science: 87
Social: 67

Student: Sia
Maths: 78
English: 56
science: 46
Social: 90

Student: Lia
Maths: 98
English: 89
science: 90
Social: 78


**DATA COMBINATION**

In [7]:
print(f"{'Name':^10}", end="")
for subj in subjects:
    print(f"{subj:^8}", end="")
print()

# Print student marks
for i, stud in enumerate(student):
    print(f"{stud:^10}", end="")
    for j, subj in enumerate(subjects):
        print(f"{marks[i, j]:^8}", end="")
    print()


   Name    Maths  English science  Social 
  Akhil      89      56      87      67   
   Sia       78      56      46      90   
   Lia       98      89      90      78   


Adding new students and Marks

In [8]:
print(student)

new_students = np.array(['Rahul', 'Priya'])
new_marks = np.array([[90, 85, 95, 80],
                      [85, 90, 80, 95]])

students = np.append(student, new_students)
marks = np.vstack((marks, new_marks))





['Akhil' 'Sia' 'Lia']


In [9]:

print(f"{'Name':^10}", end="")
for subj in subjects:
    print(f"{subj:^8}", end="")
print()

for i, stud in enumerate(students):
    print(f"{stud:^10}", end="")
    for mark in marks[i]:
        print(f"{mark:^8}", end="")
    print()

   Name    Maths  English science  Social 
  Akhil      89      56      87      67   
   Sia       78      56      46      90   
   Lia       98      89      90      78   
  Rahul      90      85      95      80   
  Priya      85      90      80      95   


**DATA MODIFICATION**

In [10]:
marks[0] = [90, 80, 85, 95]  # Update marks for Akhil
print("\nUpdated marks for Akhil:")
print(f"{'Name':^10}", end="")
for subj in subjects:
    print(f"{subj:^8}", end="")
print()

for i, stud in enumerate(students):
    print(f"{stud:^10}", end="")
    for mark in marks[i]:
        print(f"{mark:^8}", end="")
    print()


Updated marks for Akhil:
   Name    Maths  English science  Social 
  Akhil      90      80      85      95   
   Sia       78      56      46      90   
   Lia       98      89      90      78   
  Rahul      90      85      95      80   
  Priya      85      90      80      95   


In [11]:
new_subject = np.array([80, 75, 90, 85, 95])  # New subject marks
marks = np.column_stack((marks, new_subject))  # Add new subject marks
subjects = np.append(subjects, 'History')  # Add new subject name

print("\nUpdated data with new subject:")
print(f"{'Name':^10}", end="")
for subj in subjects:
    print(f"{subj:^8}", end="")
print()

for i, stud in enumerate(students):
    print(f"{stud:^10}", end="")
    for mark in marks[i]:
        print(f"{mark:^8}", end="")
    print()


Updated data with new subject:
   Name    Maths  English science  Social History 
  Akhil      90      80      85      95      80   
   Sia       78      56      46      90      75   
   Lia       98      89      90      78      90   
  Rahul      90      85      95      80      85   
  Priya      85      90      80      95      95   


In [12]:
students = np.delete(students, 0)  # Delete first student (Akhil)
marks = np.delete(marks, 0, axis=0)  # Delete marks for first student

print("\nUpdated data after deleting Akhil:")
print(f"{'Name':^10}", end="")
for subj in subjects:
    print(f"{subj:^8}", end="")
print()

for i, stud in enumerate(students):
    print(f"{stud:^10}", end="")
    for mark in marks[i]:
        print(f"{mark:^8}", end="")
    print()



Updated data after deleting Akhil:
   Name    Maths  English science  Social History 
   Sia       78      56      46      90      75   
   Lia       98      89      90      78      90   
  Rahul      90      85      95      80      85   
  Priya      85      90      80      95      95   


**DATA TYPE HANDLING**

In [13]:
result_int = marks / 2
result_float = marks / 2

print("Integer Division ( NumPy handles integer division differently than Python):")
print(result_int)
print("Float Division:")
print(result_float)

Integer Division ( NumPy handles integer division differently than Python):
[[39.  28.  23.  45.  37.5]
 [49.  44.5 45.  39.  45. ]
 [45.  42.5 47.5 40.  42.5]
 [42.5 45.  40.  47.5 47.5]]
Float Division:
[[39.  28.  23.  45.  37.5]
 [49.  44.5 45.  39.  45. ]
 [45.  42.5 47.5 40.  42.5]
 [42.5 45.  40.  47.5 47.5]]


In [14]:
result_int_div_float = marks / 2.0
print("\nInteger array divided by a float:")
print(result_int_div_float)


Integer array divided by a float:
[[39.  28.  23.  45.  37.5]
 [49.  44.5 45.  39.  45. ]
 [45.  42.5 47.5 40.  42.5]
 [42.5 45.  40.  47.5 47.5]]


**COPY AND VIEW BEHAVIOR**

In [15]:
full_copy = marks.copy()

view = marks.view()

print("Original Array:")
print(marks)

print("\nFull Copy:")
print(full_copy)

print("\nView:")
print(view)

# Modifying the original array
marks[0, 0] = 100

print("\nAfter modifying the original array:")

print("Original Array:")
print(marks)

print("\nFull Copy:")
print(full_copy)

print("\nView:")
print(view)



Original Array:
[[78 56 46 90 75]
 [98 89 90 78 90]
 [90 85 95 80 85]
 [85 90 80 95 95]]

Full Copy:
[[78 56 46 90 75]
 [98 89 90 78 90]
 [90 85 95 80 85]
 [85 90 80 95 95]]

View:
[[78 56 46 90 75]
 [98 89 90 78 90]
 [90 85 95 80 85]
 [85 90 80 95 95]]

After modifying the original array:
Original Array:
[[100  56  46  90  75]
 [ 98  89  90  78  90]
 [ 90  85  95  80  85]
 [ 85  90  80  95  95]]

Full Copy:
[[78 56 46 90 75]
 [98 89 90 78 90]
 [90 85 95 80 85]
 [85 90 80 95 95]]

View:
[[100  56  46  90  75]
 [ 98  89  90  78  90]
 [ 90  85  95  80  85]
 [ 85  90  80  95  95]]
